use_frameworks!

platform :ios, '14.0'

target 'DSRE_Example' do
  pod 'DSRE', :path => '../'
  
  pod 'Alamofire', '~> 5.0'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'SnapKit'
  pod 'SwifterSwift/UIKit'
  pod 'SDWebImage'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
end

target 'DSRE_Example_Child' do
  pod 'DSRE', :path => '../'
  
  pod 'Alamofire', '~> 5.0'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'SnapKit'
  pod 'SwifterSwift/UIKit'
  pod 'SVProgressHUD'
end
